Migration to spring3/jakarta/java17
eclipse-basyx/basyx-java-server-sdk pull request #139
Opened 2023-11-16 07:45 UTC by alexgordtop

2023-11-16 12:57 UTC, FrankSchnicke commented
Closes https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/113

2023-11-29 14:34 UTC, mdanish98 requested changes
Following are some of the review remarks:

2023-11-29 14:45 UTC, alexgordtop commented
@mdanish98 I can't activate the kafka modules, since they aren't spring3 ready - in their current configuration. @FrankSchnicke and @geso02 agreed on this and @geso02 will contribute related changes as soon as this pull request is merged.

2023-11-29 15:08 UTC, mdanish98 commented
@alexgordtop yes sure I am removing those remarks.

2023-11-29 16:53 UTC, alexgordtop commented on basyx.common/basyx.http/pom.xml
> +		<dependency>
Now it's required - for e.g. Base64UrlEncodedIdentifierSizeValidator

2023-11-30 12:38 UTC, mdanish98 approved these changes
Approved

2023-11-30 12:39 UTC, merged

2023-11-30 12:39 UTC, FrankSchnicke commented
Thanks a lot!