Implements authorization for ConnectedAasManager
eclipse-basyx/basyx-java-server-sdk pull request #307
Opened 2024-06-04 13:00 UTC by mdanish98

The current implementation of [ConnectedAasManager](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.aasenvironment/basyx.aasenvironment-client/src/main/java/org/eclipse/digitaltwin/basyx/aasenvironment/client/ConnectedAasManager.java) should be extended to enable authorized requests. 

This PR implements authorized versions of below Connected components:
- Implements authorization for ConnectedAasManager
- Implements authorization for ConnectedAasRepository
- Implements authorization for ConnectedAasService
- Implements authorization for ConnectedSubmodelRepository
- Implements authorization for ConnectedSubmodelService

Signed-off-by: Mohammad Ghazanfar Ali Danish <ghazanfar.danish@iese.fraunhofer.de>

2024-06-10 11:35 UTC, mateusmolina-iese requested changes

2024-06-10 11:35 UTC, mateusmolina-iese commented on basyx.aasregistry/basyx.aasregistry-service-release-kafka-mongodb/src/test/java/org/eclipse/digitaltwin/basyx/aasregistry/service/storage/mongodb/AuthorizedClientTest.java
> +		// TODO: It uses normal GET unauthorized request, need to override and refactor
Are you implementing in the scope of the PR?

2024-06-10 11:35 UTC, mateusmolina-iese commented on basyx.aasregistry/basyx.aasregistry-service-release-kafka-mongodb/src/test/java/org/eclipse/digitaltwin/basyx/aasregistry/service/storage/mongodb/AuthorizedClientTest.java
> +		// TODO: It uses normal GET unauthorized request, need to override and refactor
Are you implementing in the scope of the PR?

2024-06-10 11:35 UTC, mateusmolina-iese commented on basyx.submodelregistry/basyx.submodelregistry-service-release-kafka-mongodb/src/test/java/org/eclipse/digitaltwin/basyx/submodelregistry/service/storage/mongodb/AuthorizedClientTest.java
> +		// TODO: It uses normal GET unauthorized request, need to override and refactor
Are you implementing in the scope of the PR?

2024-06-10 11:35 UTC, mateusmolina-iese commented on basyx.submodelservice/basyx.submodelservice-client/pom.xml
> +			<scope>test</scope>
using this pom as reference, but applies to all changed poms: did you run mvn dependency:analyze to see if all the added deps are used?

2024-06-11 08:56 UTC, mdanish98 commented on ci/docker-compose.yml
> +      dockerfile_inline: |
Done

2024-06-11 09:01 UTC, mdanish98 commented on examples/keycloak/initializer/src/main/java/org/eclipse/digitaltwin/basyx/keycloak/initializer/InitializerSpi.java
> +public class InitializerSpi implements Spi {
Done

2024-06-11 09:01 UTC, mdanish98 commented on basyx.aasregistry/basyx.aasregistry-client-native/pom.xml
> +			<plugin>
Removed

2024-06-11 09:03 UTC, mdanish98 commented on basyx.submodelregistry/basyx.submodelregistry-client-native/hs_err_pid14700.log
Done

2024-06-11 09:03 UTC, mdanish98 commented on basyx.submodelregistry/basyx.submodelregistry-client-native/hs_err_pid70168.log
Done

2024-06-11 09:04 UTC, mdanish98 commented on basyx.aasregistry/basyx.aasregistry-service-release-log-mem/hs_err_pid21812.log
Done

2024-06-11 09:04 UTC, mdanish98 commented on basyx.aasregistry/basyx.aasregistry-service-release-log-mem/hs_err_pid68424.log
Done

2024-06-13 12:59 UTC, mateusmolina-iese approved these changes

2024-06-13 13:36 UTC, merged