Adds authorization support for preconfigured AAS Environment
eclipse-basyx/basyx-java-server-sdk pull request #325
Opened 2024-06-20 13:19 UTC by FriedJannik

2024-07-04 12:37 UTC, mateusmolina-iese commented on basyx.aasenvironment/basyx.aasenvironment.component/pom.xml
>  			<artifactId>httpclient5</artifactId>
Is this change necessary?

2024-07-04 12:37 UTC, mateusmolina-iese commented on basyx.common/basyx.client/src/main/java/org/eclipse/digitaltwin/basyx/client/internal/authorization/AccessTokenProviderFactory.java
> +    public AccessTokenProvider create(){
Consider adding unit tests to this factory

2024-07-10 07:14 UTC, jannikf02 commented on basyx.aasenvironment/basyx.aasenvironment-core/src/main/java/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/AasEnvironmentPreconfigurationLoader.java
> +		if(authorizationEnabled) {
We need this part here, because we need to authorize the Action performed by the PreConfiguration Loader, so imo it is not possible to extract this

2024-07-23 08:15 UTC, mateusmolina-iese requested changes

2024-07-23 08:15 UTC, mateusmolina-iese commented on basyx.aasenvironment/basyx.aasenvironment-feature-authorization/src/test/java/org/eclipse/digitaltwin/basyx/aasenvironment/feature/authorization/DummyAasEnvironmentConfiguration.java
> +import org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader;
Imports not needed

2024-07-23 08:15 UTC, mateusmolina-iese commented on basyx.aasenvironment/basyx.aasenvironment.component/pom.xml
> +			<artifactId>basyx.client</artifactId>
Is this dep. required?

2024-07-23 11:46 UTC, merged