Added test methods for submodelrepository and submodelservice
eclipse-basyx/basyx-java-server-sdk pull request #335
Opened 2024-07-10 14:51 UTC by VivekHub97

This PR adds missing test methods in the submodelrepository and submodelservice test suite.

2024-08-09 10:04 UTC, mdanish98 requested changes

2024-08-09 10:04 UTC, mdanish98 commented on basyx.submodelservice/basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java
> +		assertEquals(submodel.getSubmodelElements().size(),patchedSubmodel.getSubmodelElements().size());
Please add vertical space above this line.

2024-08-19 18:00 UTC, mdanish98 requested changes

2024-08-20 13:12 UTC, mdanish98 approved these changes

2024-08-21 07:14 UTC, aaronzi requested changes

2024-08-21 07:14 UTC, aaronzi commented on basyx.submodelrepository/basyx.submodelrepository-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/core/SubmodelRepositorySuite.java
Please update the License header to 2024

2024-08-21 07:14 UTC, aaronzi commented on basyx.submodelservice/basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java
Please update the license header to 2024

2024-08-21 08:15 UTC, aaronzi approved these changes

2024-08-21 08:15 UTC, merged