MQTT for SubmodelService
eclipse-basyx/basyx-java-server-sdk pull request #339
Opened 2024-07-17 15:29 UTC by masud-svg

2024-07-31 06:36 UTC, mdanish98 reviewed
Please use BaSyx Formatter for all files.

2024-07-31 07:10 UTC, mdanish98 requested changes

2024-08-22 09:28 UTC, masud-svg commented on basyx.submodelservice/basyx.submodelservice-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/feature/mqtt/MqttSubmodelServiceConfiguration.java
> + */
updated

2024-08-22 09:28 UTC, masud-svg commented on basyx.submodelservice/basyx.submodelservice-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/feature/mqtt/MqttSubmodelServiceTopicFactory.java
> +	private static final String SUBMODELSERVIC = "sm-service";
updated

2024-08-22 09:28 UTC, masud-svg commented on basyx.submodelservice/basyx.submodelservice-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/feature/mqtt/MqttSubmodelServiceTopicFactory.java
> +	private static final String SUBMODELELEMENTS = "submodelElements";
updated

2024-08-22 09:28 UTC, masud-svg commented on basyx.submodelservice/basyx.submodelservice-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/feature/mqtt/MqttSubmodelServiceTopicFactory.java
> +	 * @param encoder
updated

2024-08-22 09:28 UTC, masud-svg commented on basyx.submodelservice/basyx.submodelservice-feature-mqtt/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/feature/mqtt/TestMqttSubmodelObserver.java
> +public class TestMqttSubmodelObserver {
added

2024-08-26 15:08 UTC, mdanish98 approved these changes
Approved

2024-08-26 15:21 UTC, aaronzi requested changes

2024-08-26 15:21 UTC, aaronzi commented on basyx.submodelservice/basyx.submodelservice-feature-mqtt/pom.xml
> +		<dependency>
Duplicate dependency. Please remove

2024-08-27 10:58 UTC, merged