Implement Remaining MQTTSubmodelRepo Methods
eclipse-basyx/basyx-java-server-sdk pull request #544
Opened 2024-11-26 06:48 UTC by ShehriyarShariq-Fraunhofer

Implemented eventing logic + tests for:
1. patchSubmodelElements
2. setFileValue
3. deleteFileValue

Closes #428

2024-11-29 07:42 UTC, mateusmolina-iese requested changes

2024-11-29 07:42 UTC, mateusmolina-iese commented on basyx.submodelrepository/basyx.submodelrepository-feature-mqtt/Readme.md
> +| FileValue Updated | sm-repository/$repoId/submodels/$submodelIdBase64URLEncoded/submodelElements/$idShortPath/fileValue/$fileName/updated | Updated SubmodelElement JSON  |
Can you please change the topic to match the spec [1, 2]? Also, no need for the `$fileName` in the topic itself.

[1] https://app.swaggerhub.com/apis/Plattform_i40/SubmodelServiceSpecification/V3.0.1_SSP-001#/Submodel%20API/PutFileByPath
[2] https://app.swaggerhub.com/apis/Plattform_i40/SubmodelServiceSpecification/V3.0.1_SSP-001#/Submodel%20API/DeleteFileByPath

2024-12-03 14:14 UTC, mateusmolina-iese approved these changes

2024-12-03 14:34 UTC, mateusmolina-iese requested changes

2024-12-03 14:34 UTC, mateusmolina-iese commented on basyx.submodelrepository/basyx.submodelrepository-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/feature/mqtt/MqttSubmodelRepository.java
> +		List<SubmodelElement> patchedSubmodelElements = decorated.getSubmodelElements(submodelId, PaginationInfo.NO_LIMIT).getResult();
Is there any reason to use the NO_LIMIT request to get the patched submodel elements again? They are already being passed as parameter.

2024-12-06 07:33 UTC, aaronzi approved these changes

2024-12-06 07:33 UTC, merged