Adds Component for Submodel Service
eclipse-basyx/basyx-java-server-sdk pull request #58
Opened 2023-07-17 12:49 UTC by FriedJannik

2023-07-20 11:33 UTC, jannisjung requested changes
Please Resolve the review Remarks

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
declare as used

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-20 11:33 UTC, jannisjung commented on basyx.submodelservice/basyx.submodelservice-http/pom.xml
> +		<dependency>
unused; remove

2023-07-28 08:14 UTC, jannisjung approved these changes
approved

2023-08-03 08:49 UTC, FrankSchnicke commented on basyx.submodelservice/basyx.submodelservice-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/http/SubmodelServiceSubmodelElementsTestSuiteHTTP.java
> +	public void delteNestedSubmodelElementFromSubmodelElementList()
Typo in "delete"

2023-08-03 08:49 UTC, FrankSchnicke commented on basyx.submodelservice/basyx.submodelservice-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/http/SubmodelServiceSubmodelElementsTestSuiteHTTP.java
> +		// delete first element of the submodel element list
Please remove this comment

2023-08-03 09:55 UTC, merged