Integrate AAS4J serialization into SwaggerUI
eclipse-basyx/basyx-java-server-sdk pull request #92
Opened 2023-09-22 12:55 UTC by mdanish98

- Applies mixins but does not take ReflectionAnnotationIntrospector into consideration (Need to analyse more)

Signed-off-by: Mohammad Ghazanfar Ali Danish <ghazanfar.danish@iese.fraunhofer.de>

2023-09-25 06:56 UTC, FrankSchnicke requested changes

2023-09-25 06:56 UTC, FrankSchnicke commented on basyx.common/basyx.http/src/main/java/org/eclipse/digitaltwin/basyx/http/documentation/RepositoryApiDocumentationConfiguration.java
> +		SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, org.springdoc.core.converters.models.MonetaryAmount.class);
Is this still needed for this PR?

2023-10-06 11:08 UTC, mdanish98 commented on basyx.common/basyx.http/src/main/java/org/eclipse/digitaltwin/basyx/http/documentation/RepositoryApiDocumentationConfiguration.java
> +		SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, org.springdoc.core.converters.models.MonetaryAmount.class);
I removed this static block.

2023-10-06 11:09 UTC, FrankSchnicke approved these changes

2023-10-06 14:05 UTC, merged